### PR TITLE
Add callback to joystick

### LINKED ISSUE #20: Allow AddListener/Callback
Currently, you have to use setTimout. Is there a way to do this with listeners/callbacks, and if there isn't could you add the ability? This would be **greatly** appreciated.

### PR DESCRIPTION
**Pull request by kethan1**
Fixes #20 

JSFiddle: https://jsfiddle.net/KetZoomer/p9av2y5h/

### CODE REVIEW

**Comment by kethan1** [comment]
Updated minified file

**Comment by kethan1** [comment]
@bobboteck could you please take a look at this PR

**Comment by bobboteck** [comment]
As I write in the Issue #20 close this pull request to work on a new version

**Comment by kethan1** [comment]
I see. Didn't realize the code was bugged. Hope it helps though!

**Pull request closed without merging**
