### PR TITLE
Support multiple joysticks

### PR DESCRIPTION
**Pull request by brollin**
I saw the other pull request for fixing this same problem, but I think this solution may be cleaner.

Support multiple joysticks by saving the ID of the touch point when a canvas is touched. Then when a touch is ended anywhere in the document, each joystick compares the ended touch ID with the touch ID associated with its canvas to know whether to honor that touch end event.

By the way, didn't see a way to generate the minified JS. Would recommend including a command to do so somewhere, perhaps as a npm script.

### CODE REVIEW

**Comment by nguterresn** [comment]
Absolutely agree with you. This one looks like an easy and clean fix.

Is anyone maintaining this repo? Would like to fix this officially on my side as well!

**Comment by top-kat** [comment]
@bobboteck any plans on merging this ? This would be very helpful :)

**Comment by bobboteck** [comment]
@top-kat @nguterresn @brollin sorry for late merge, but I'm too busy in this period of my life, can you test if all is ok?

**Comment by topkat** [comment]
Tested everything is working fine :) Thanks a lot @bobboteck and good luck to handle everything ;)

**Comment by top-kat** [comment]
@bobboteck can't wait for #44 to be merged to, this will be a huge improvement also

**Pull request merged**
